### ISSUE TITLE
Serving static asset

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/py-skygear#20]
We want to support serving static asset, which will be helpful in plugin that bundles with a static web app that talks to the skygear server API.

It is proposed that plugin and cloudcode developer need to use a new decorator `static_assets` to decorate a function that returns the path of static assets location in the file system. The static assets in the directory are available at the URL prefix specified in the decorator.

```python
# example
@static_assets(prefix='/admin_page')
def my_assets():
    return "/path/to/static/assets"
```

The py-skygear library should implement helper function so that developer only need to specify a directory within its projects.

Static assets from plugins will be included when py-skygear follow the import graph if `@static_assets` is defined in the plugin.

In the above example, the file `/path/to/static/assets/login.html` will be available at `https://exampleapp.skygeario.com/static/admin_page/login.html`. 

Since all declaration for static assets share the same URL namespace, plugin developer should prefix their `static_assets` URL with the name of the plugin.

```
@static_assets(prefix='/chat/portal')
def chat_portal_asset():
    return "/path/to/static/assets"
```

Tasks:

* [x] Add `static_assets` decorator #21
* [x] The `static_assets` decorator need to implement handler extension point so that static assets are served to the client via plugin transport and skygear-server #23
* [x] Helper function to return absolute path #21
* [x] Entry point to collect static assets for cloud deployment #22

**Comment by cheungpat** [comment]
This was implemented in https://github.com/SkygearIO/py-skygear/releases/tag/v0.13.0
